path: /Users/Robin1/Desktop/LIDAR Project/2D-Vehicle-Classification/data
train: ./images/train # train images (relative to 'path')
val: ./images/val # val images (relative to 'path')

# Classes
names:
  0: car
  1: pickup
  2: SUV
  3: van
  4: truck
  5: bus
  6: motorcycle
  7: pedestrian
